server:
  port: 9755

spring:
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）

logging:
  level:
    console: INFO
    filter: INFO

zuihou:
  file:
    upload-path: D:\home\uploadfile\
    remote-uri-prefix: http://192.168.65.147:6080/