server:
  port: 9755

fileServer:
  domain: http://10.28.1.136:8888

files:
  docservice:
    url: http://127.0.0.1/web-apps/apps/api/documents/api.js

spring:
  application:
    name: zuihou-file-server
  profiles:
    active: dev
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
    service:
      name: zuihou-zipkin
    locator:
      discovery:
        enabled: true

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
#    hostname: ${eureka.hostname:eureka.zuihou.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

management:
  security:
    enabled: true
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

zuihou:
  file:
    upload-path: /home/uploadfile/
    remote-uri-prefix: http://192.168.65.147:6080/
