server:
  port: 9775

spring:
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）

zuihou:
  mysql:
    admin:
      database: zuihou_admin_dev

logging:
  level:
    console: INFO
    filter: INFO

id-generator:
  machine-code: 1  # id生成器机器掩码