spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://zuihou.mysql.host:3306/zuihou_zipkin_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false

