server:
  port: 10000
  
spring:
  redis:
    key-prefix: dev

logging:
  common-pattern: '%d{HH:mm:ss.SSS}:[%5p] [%t] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    rest: INFO
    service: INFO
    sql: DEBUG

zuihou:
  mysql:
    admin:
      database: zuihou_admin_dev       # 根据环境更改

id-generator:
  machine-code: 1  # id生成器机器掩码

test: dev_修改2
hello: dev_hello_修改2
