server:
  port: 10001

spring:
  redis:
    key-prefix: prod  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）

logging:
  level:
    console: WARN
    rest: WARN
    service: WARN
    sql: WARN

zuihou:
  mysql:
    admin:
      database: zuihou_admin_prod       # 根据环境更改

test: prod1 修改
hello: prod_hello_1修改啊
