server:
  port: 10000
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
#    hostname: ${eureka.hostname:eureka.zuihou.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

spring:
  application:
    name: zuihou-admin
  rabbitmq:
    host: zuihou.rabbitmq.host
    port: 5672
    password: guest
    username: guest
  redis:
    host: zuihou.redis.host
    port: 6379
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 8
      max-wait: 100
    key-prefix: dev

management:
  security:
    enabled: true
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

info:
  contact:
    email: tangstruggle@sina.com
    phone: 10086
  app: 后台管理服务

dozer:
  mappingFiles: classpath*:dozer/*.dozer.xml

zuihou:
  mysql:
    admin:
      database: zuihou_admin_dev       # 根据环境更改
      driverClassName: ${zuihou.mysql.driverClassName}
      host: ${zuihou.mysql.host}
      password: ${zuihou.mysql.password}
      port: ${zuihou.mysql.port}
      url: jdbc:mysql://${zuihou.mysql.admin.host}:${zuihou.mysql.admin.port}/${zuihou.mysql.admin.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true
      username: ${zuihou.mysql.username}
    driverClassName: com.mysql.jdbc.Driver
    host: zuihou.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==